services:
  nginx:
    container_name: nginx
    build: .
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./public:/usr/share/nginx/html
    ports:
      - "80:80"
  mysql:
    container_name: mysql
    restart: unless-stopped
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "my_db"
    ports:
      - "3306:3306"